# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-13 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('units', models.CharField(choices=[('grams', 'Grams'), ('ounces', 'Ounces'), ('kilograms', 'KIlograms'), ('pounds', 'Pounds'), ('milliliters', 'Milliliters'), ('LITERS', 'Liters'), ('cup', 'Cup'), ('scoop', 'Scoop'), ('piece', 'Piece'), ('can', 'Can')], default='grams', max_length=15)),
                ('dateTimeAdded', models.DateTimeField(auto_now_add=True)),
                ('mealType', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='breakfast', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('fats', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('calories', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('servingSize', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('units', models.CharField(choices=[('grams', 'Grams'), ('ounces', 'Ounces'), ('kilograms', 'KIlograms'), ('pounds', 'Pounds'), ('milliliters', 'Milliliters'), ('LITERS', 'Liters'), ('cup', 'Cup'), ('scoop', 'Scoop'), ('piece', 'Piece'), ('can', 'Can')], default='grams', max_length=15)),
                ('caloriesPerServing', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('proteinPerServing', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('carbohydratesPerServing', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('fatsPerServing', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='counter.Meal'),
        ),
    ]
