# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-15 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_goal_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='goal',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='goal',
            name='fats',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='goal',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
