# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-17 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20180114_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
