# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-17 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_goal_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='dateAdded',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
