# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-20 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_auto_20180117_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='caloriesPerServing',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbohydratesPerServing',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fatsPerServing',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='meal',
            name='proteinPerServing',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='meal',
            name='servingSize',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
