# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-20 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0007_auto_20180119_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='servingSize',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
