# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-20 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0008_auto_20180119_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='caloriesPerServing',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Calories Per Serving'),
        ),
    ]
