# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-09 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0012_auto_20180208_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='dateTimeAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
