# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-20 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0013_meal_datetimeadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='units',
            field=models.CharField(choices=[('grams', 'Grams'), ('ounces', 'Ounces'), ('kilograms', 'KIlograms'), ('pounds', 'Pounds'), ('milliliters', 'Milliliters'), ('liters', 'Liters'), ('cup', 'Cup'), ('scoop', 'Scoop'), ('piece', 'Piece'), ('can', 'Can'), ('unit', 'Unit')], default='grams', max_length=15),
        ),
    ]
