# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-27 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0014_auto_20180219_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='dateTimeAdded',
            field=models.DateTimeField(),
        ),
    ]
